# Template:
# [filter name]
# title = "title shown in the window"
# (optional) color = "some color" (The color of the filter.
#                    accepted colors: https://inventwithpython.com/blog/complete-list-tkinter-colors-valid-and-tested.html)
#                    (defaults to green)
# (optional) text_color = "some color" (The color of the filter's text. Same rules as above) (defaults to black)
# (optional) bind = "some keybind (ctrl + x, alt + 2, `, ?, etc...)"
# (optional) suppress = true / false (true: this keypress isn't shown to the rest of your computer) (defaults to false)
# (optional) group = "name of the group" (affects exclusve)
# (optional) exclusive = true / false (true: only one filter in the same group can be on at once)   (defaults to false)
# (optional) always_load = true / false (true: always load this filter into memory. false: this filter can be unloaded if not used.
#                                        this is useful for LLM filters that add memory pressure even when disabled.)
# action / actions = SEE OTHER SECTION

# --- action ---
# action = "path/to/python/file.py" (filter to enable/disable)
#
# action option section: some actions require extra settings.
# add them here!
# [filter name.action_options]
# some_setting = "defined by your scripts!"
#   access the action_options within shared.PluginLoadingState.action_options.
# ---        ---
# This is mutually exclusive with actions. You can either one or the other.
# --------------

# --- actions ---
# actions = ["first action name", "second action name"]
# ---         ---
# The action names have to be unique, and can't collide with any of the other keys,
# such as title, text_color, group, etc.
# Define the actions as:
# ---         ---
# [filter_name.first action name]
# type = "script" or "filter" or "prompt"
#
# If it is a script:
# script = "path/to/python/file.py" (filter to enable / disable)
#
# If it is a filter:
# mode = "enable" or "disable"
# filter = "name of the filter"
#
# If it is a prompt:
# prompt = "Some system prompt..."
# ---------------

[rage]
title = "Rage"
bind = "unbound"
actions = ["caps", "excited"]

[qwen_postprocess]
title = "Qwen"
bind = "unbound"
action = "filters/qwen_postprocess.py"

[qwen_postprocess.action_options]
prompt = """You are a deterministic text transformation engine.
Output only transformed text.
Do not explain.
Do not answer questions.
Transform the transcript as if it was spoken by a well-educated and flowery speaker."""

[binary]
title = "Binary"
bind = "unbound"
group = "radio"
exclusive = true
color = "dark blue"
text_color = "white"
action = "filters/binary.py"

[cargo]
title = "Cargo"
bind = "unbound"
group = "radio"
exclusive = true
color = "DarkGoldenrod1"
text_color = "black"
action = "filters/cargo.py"

[command]
title = "Command"
bind = "unbound"
group = "radio"
exclusive = true
color = "DeepPink"
text_color = "black"
action = "filters/command.py"

[engineering]
title = "Engineering"
bind = "unbound"
group = "radio"
exclusive = true
color = "DarkOrange"
text_color = "black"
action = "filters/engineering.py"

[medical]
title = "Medical"
bind = "unbound"
group = "radio"
exclusive = true
color = "aqua"
text_color = "black"
action = "filters/medical.py"

[science]
title = "Science"
bind = "unbound"
group = "radio"
exclusive = true
color = "purple"
text_color = "white"
action = "filters/science.py"

[security]
title = "Security"
bind = "unbound"
group = "radio"
exclusive = true
color = "red"
text_color = "black"
action = "filters/security.py"

[all_caps]
title = "CAPS"
action = "filters/all_caps.py"

[excited]
title = "!!!"
action = "filters/excited.py"

[rage.caps]
type = "filter"
name = "all_caps"

[rage.excited]
type = "filter"
name = "excited"