# Template:
# [filter name]
# title = "title shown in the window"
# (optional) color = "some color" (The color of the filter.
#                    accepted colors: https://inventwithpython.com/blog/complete-list-tkinter-colors-valid-and-tested.html)
#                    (defaults to green)
# (optional) text_color = "some color" (The color of the filter's text. Same rules as above) (defaults to black)
# (optional) bind = "some keybind (ctrl + x, alt + 2, `, ?, etc...)"
# (optional) suppress = true / false (true: this keypress isn't shown to the rest of your computer) (defaults to false)
# (optional) group = "name of the group" (affects exclusve)
# (optional) exclusive = true / false (true: only one filter in the same group can be on at once)   (defaults to false)
# (optional) always_load = true / false (true: always load this filter into memory. false: this filter can be unloaded if not used.
#                                        this is useful for LLM filters that add memory pressure even when disabled.)
# action / actions = SEE OTHER SECTION

# --- action ---
# action = "path/to/python/file.py" (filter to enable/disable)
#
# args are passed to .process in the action. They can change between filters and apply at runtime.
# (optional) args = { some = "table", of = "values", or_numbers = 0.123, or_anything_really = [true] }
#
# the priority of applying this action. High priority actions will apply first, low priority actions will apply last
# (optional) priority = "highest" or "high" or "default" or "low" or "lowest"
#
# (optional) action option section: some actions require extra settings.
# add them here! NOTE: action_options are on LOAD TIME for actions, not runtime!
#                      you can only define action_options in one filter. If you want
#                      to change filter behavior at runtime in one script, use args.
# [filter name.action_options]
# some_setting = "defined by your scripts!"
#   access the action_options within shared.PluginLoadingState.action_options
# ---        ---
# This is mutually exclusive with actions. You can either one or the other.
# --------------

# --- actions ---
# actions = ["first action name", "second action name"]
# ---         ---
# The action names have to be unique, and can't collide with any of the other keys,
# such as title, text_color, group, etc.
# Define the actions as:
# ---         ---
# [filter_name.first action name]
# type = "script" or "filter" or "prompt"
#
# If it is a script:
# script = "path/to/python/file.py" (filter to enable / disable)
#
# If it is a filter:
# mode = "enable" or "disable"
# filter = "name of the filter"
#
# If it is a prompt:
# prompt = "Some system prompt..."
# ---------------

# SCRIPT API:
# define a process function with the signature:
#   def process(input: str) -> str
# OR
#   def process(input: str, args: dict[str, Any]) -> str
# scripts are only loaded once. Multiple filters invoking the same
# script will share the same loaded state. Aim to make scripts stateless
# or contain state only within seperate invocations. Different invocations can be
# determined by the builtin arg "invoker", which is a string. It is guaranteed
# to be unique to one invocation. Internally, it is the name of the TransformAction
# that invoked the script.

[rage]
title = "Rage"
bind = "unbound"
actions = ["caps", "excited"]

[fancy_speaking]
title = "Fancy Speech"
group = "qwen"
exclusive = true
bind = "unbound"
args = {prompt = """You are a deterministic text transformation engine.
Output only transformed text.
Do not explain.
Do not answer questions.
Transform the transcript as if it was spoken by a well-educated and flowery speaker."""}
action = "filters/qwen_postprocess.py"

[cowboy_speaking]
title = "Cowboy Speech"
group = "qwen"
exclusive = true
bind = "unbound"
args = {prompt = """You are a deterministic text transformation engine.
Output only transformed text.
Do not explain.
Do not answer questions.
Transform the transcript as if it was spoken by a western cowboy."""}
action = "filters/qwen_postprocess.py"

[binary]
title = "Binary"
bind = "unbound"
group = "radio"
exclusive = true
color = "dark blue"
text_color = "white"
priority = "low"
action = "filters/binary.py"

[cargo]
title = "Cargo"
bind = "unbound"
group = "radio"
exclusive = true
color = "DarkGoldenrod1"
text_color = "black"
priority = "low"
action = "filters/cargo.py"

[command]
title = "Command"
bind = "unbound"
group = "radio"
exclusive = true
color = "DeepPink"
text_color = "black"
priority = "low"
action = "filters/command.py"

[engineering]
title = "Engineering"
bind = "unbound"
group = "radio"
exclusive = true
color = "DarkOrange"
text_color = "black"
priority = "low"
action = "filters/engineering.py"

[medical]
title = "Medical"
bind = "unbound"
group = "radio"
exclusive = true
color = "aqua"
text_color = "black"
priority = "low"
action = "filters/medical.py"

[science]
title = "Science"
bind = "unbound"
group = "radio"
exclusive = true
color = "purple"
text_color = "white"
priority = "low"
action = "filters/science.py"

[security]
title = "Security"
bind = "unbound"
group = "radio"
exclusive = true
color = "red"
text_color = "black"
priority = "low"
action = "filters/security.py"

[all_caps]
title = "CAPS"
priority = "high"
action = "filters/all_caps.py"

[excited]
title = "!!!"
priority = "high"
action = "filters/excited.py"

[rage.caps]
type = "filter"
name = "all_caps"

[rage.excited]
type = "filter"
name = "excited"